# Generated by Django 5.0 on 2024-02-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscard',
            name='tarefa_card',
            field=models.CharField(max_length=50),
        ),
    ]
