# Generated by Django 5.0 on 2024-02-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_dadoscard_tarefa_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscard',
            name='tarefa_card',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
