# Generated by Django 5.0 on 2024-02-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_dadoscard_tarefa_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscard',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dadoscard',
            name='tarefa_card',
            field=models.CharField(max_length=50),
        ),
    ]
