# Generated by Django 5.0 on 2024-02-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_dadoscard_done_alter_dadoscard_tarefa_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefasCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dadoscard',
            name='done',
        ),
    ]
