# Generated by Django 5.0 on 2024-02-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_tarefascard_remove_dadoscard_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosCard',
        ),
        migrations.DeleteModel(
            name='TarefasCard',
        ),
    ]
