# Generated by Django 5.0 on 2024-02-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0006_delete_dadoscard_delete_tarefascard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_card', models.CharField(max_length=100)),
                ('tarefas_card', models.CharField(max_length=100)),
            ],
        ),
    ]
