# Generated by Django 5.0 on 2024-02-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=22)),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
